pipeline {
    agent any

    stages {
        stage('Unit test - Backend') {
			agent{
				docker{
					image 'snakee/golang-junit:1.21'
					reuseNode true
					args '-u root'
				}
			}
			environment {
                GOCACHE = "${WORKSPACE}/.gocache"
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
						mkdir -p $GOCACHE
                        go test ./... -v 2>&1 | go-junit-report > test-results.xml
                    '''
                }
            }
			post{
				always{
					junit 'bugtracker-backend/test-results.xml'
				}
			}
        }
		
		stage('frontend tests'){
			agent{
				docker{
					image 'node:20-alpine'
					reuseNode true
				}
			}
			
			steps{
				dir('bugtracker-frontend'){
					sh '''
						npm ci
						npm test
					'''
				}
			}
			post{
				always{
					junit 'bugtracker-frontend/test-results.xml'
				}
			}
		}
    }
}
