pipeline {
    agent any

    stages {
        stage('Unit test - Backend') {
			agent{
				docker{
					image 'snakee/golang-junit:1.21'
					reuseNode true
				}
			}
			environment {
                GOCACHE = "${WORKSPACE}/.gocache"
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p $GOCACHE
                        go test ./... -v
                    '''
                }
            }
        }
    }
}
