pipeline {
    agent any

    stages {
        stage('Unit test - Backend') {
			agent{
				docker{
					image 'snakee/golang-junit:1.21'
				}
			}
            steps {
                dir ('bugtracker-backend'){
					sh 'go test ./... -v'
				}
            }
        }
    }
}
